### ISSUE TITLE
lua 5.1 and 5.2 require bug

### ISSUE THREAD

**Issue by achan001** [pygy/require.lua#9]
reading the actual c function ll_require, it accept false as a valid return.
this is of course a bug, as it defeated the purpose of package.loaded cache table.

your lua implementation of require actually got it right, by
not allow false to get into the cache table.

until the c version is fixed, you might want to add a comment about the bug.

**Comment by achan001** [comment]
my mistake.
the lua implementation of require also allow to set false to the cache table.
this is a require bug, as it should not allow reload the same file multiple times.

**Comment by pygy** [comment]
Hi @achan001 thanks for passing by. AFAIK this is a deliberate design choice by the Lua authors.

**Comment by achan001** [comment]
it just make no sense.
only 2 values will disable package.loaded cache tables: nil and false
nil is disallowed, but false is ok ?

**Comment by achan001** [comment]
allowing false in cache table could possibly cause infinite loops,
if the modules recursively require itself (or thru other sibling modules)

a very simple fix is to consider any entry as valid:
patch:
< if module then return module end
> if module ~= nil then return module end

**Comment by achan001** [comment]
correction.
infinite loops may not happen. (false is set at the "end" of require)
But still, require is not supposed to read same file multiple times.

**Comment by achan001** [comment]
this patch will avoid require() reading the same file multiple times, even if returned false
```
<  if module then return module end
>  if module ~= nil then return module end
```

**Comment by pygy** [comment]
Just to be clear, since I haven't touched Lua in a while:

This library aims to reproduce the behavior of the native `require()` function. Are there any discrepancies? If yes, they are bugs, otherwise, there's nothing to do since Lua 5.1, 5.2 and 5.3 are done feature-wise as far as the PUC folks are concerned. 5.3 may still get bugfixes, but you'd have to convince the authors that what you describe is a bug (ie that it contradicts what the manual says. Documented and undocumented behaviors are not bugs).

**Comment by tst2005** [comment]
Hello,
The current lua-require implementation follow exactly the lua behavior.

```lua test.lua
local requires = require "require"
local req51 = requires.require51
local req52 = requires.require52

-- drop the main difference between lua5.1 and lua5.2 to be able to check all lua-require implementations
package.loaders = package.loaders or package.searchers
package.searchers = package.searchers or package.loaders

for _,require in ipairs({_G.require,req51,req52}) do
        -- reset possible loaded modules
        package.loaded.ni=nil package.loaded.fa=nil

        local n, f = 0, 0 -- counters
        package.preload.ni=function() n=n+1 return nil end
        package.preload.fa=function() f=f+1 return false end

        assert(require"ni"==true) -- 1st call, 1st load, returns nil, cached as true
        assert(require"ni"==true) -- 2nd call, no load, return true from the package.loaded cache
        assert(require"fa"==false) -- 1st call, 1st load, returns false, not cached
        assert(require"fa"==false) -- 2nd load, 2nd load, returns false, not cached
        assert(n==1) -- the "ni" module is loaded only once
        assert(f==2) -- the "fa" module is loaded each time
        print(require)
end
print("OK", _VERSION)
```

Tested on Lua 5.1/5.2/5.3 LuaJIT 2.0/2.1

Results :
```
$ for lua in lua5.1 lua5.2 lua5.3 luajit2.0 luajit2.1; do $lua test-nil-and-false.lua; done                                                                                 
function: 0x25da070
function: 0x25e2180
function: 0x25e0090
OK      Lua 5.1
function: 0x6620f0
function: 0x663900
function: 0x66a880
OK      Lua 5.2
function: 0x3eed130
function: 0x3ef5680
function: 0x3eef3a0
OK      Lua 5.3
function: 0x40f0df70
function: 0x40f12960
function: 0x40f15768
OK      Lua 5.1
function: 0x41f100a8
function: 0x41f150e8
function: 0x41f151e8
OK      Lua 5.1
```

There is nothing to fix un lua-require ;-)

**Comment by achan001** [comment]
there is nothing wrong with lua implementation of require (see post 2: "my mistake ...")

This is a quote from PIL 2nd edition, page 138:
"..., once a module is loaded, other calls to require simply return
the same value, without loading the module again"

just because the module return false does not mean it is not loaded.

this is probably a rare bug.
who will write a mod.lua that return false ?

**Comment by achan001** [comment]
I found the original proposal of require (9/17/2004)
it is funny that nil and false are not allowed in package.loaded cache table

https://marc.info/?l=lua-l&m=113878469246850&w=2
